### ISSUE TITLE
Setup directories structure and work flow for this repository 

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-design#11]

**Comment by abitrolly** [comment]
Top level - project name:
* `cyber-browser`
* `cyber.fund`
* ...

Second level names should correspond to real site URLs. For example, site root is named `home`.
* `cyber-browser/home_concept.png` - **concept** working version (wireframe)
* `cyber-browser/home_01.png` - **design version** one for the home page
* `cyber-browser/home_02.png` - **design version** two for the home page
* `cyber-browser/home_final.png` - design **working version**

Design for page that ends at `/tokens` endpoint.
* `cyber-browser/tokens_01.png` - design version one for the page **`/tokens`**
* `cyber-browser/tokens_02.png` - design version two for the page **`/tokens`**
* `cyber-browser/tokens_final.png` - **`/tokens`** design that is converted to HTML5 layout
