### ISSUE TITLE
Redesign token page

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-design#14]

**Comment by SiarheiSadau** [comment]
![token details](https://user-images.githubusercontent.com/17406355/36543496-99f785b4-17ec-11e8-89bf-c470c6df3028.png)

**Comment by SiarheiSadau** [comment]
@Olga584 
![token detailes header](https://user-images.githubusercontent.com/17406355/36588466-d9881974-1890-11e8-8ef5-d3cd9479b792.png)
