### ISSUE TITLE
Blockchains page concept

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-design#16]
- [x] Blockchains page
- [x] Blockchain detailes page

**Comment by SiarheiSadau** [comment]
![blockchains](https://user-images.githubusercontent.com/17406355/36487951-da4f0a46-172a-11e8-99fa-7833c777fb48.png)
![blockchain details](https://user-images.githubusercontent.com/17406355/36487958-dcdb068e-172a-11e8-8c48-4a4f1282b0f4.png)
