### ISSUE TITLE
Exchanges page concept

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-design#17]
- [x] Describe the functions of "Exchanges List" pages
 - [x] Describe the functions of "Exchange Details" pages

**Comment by SiarheiSadau** [comment]
Drafts of Exch list and Exch Details
![exchange list](https://user-images.githubusercontent.com/17406355/36254596-4ec11918-1254-11e8-9dc3-c08748ce625a.png)
![exchanges](https://user-images.githubusercontent.com/17406355/36254601-533e40a6-1254-11e8-85b9-14d361885591.png)

**Comment by 21xhipster** [comment]
Please add last trade time on the first screen

**Comment by 21xhipster** [comment]
A page of exchange should emphasize it's brand. Huge logo, solid h1

**Comment by 21xhipster** [comment]
Native volume data column should be in place

**Comment by SiarheiSadau** [comment]
Exchanges list page update.

![exchange list 1](https://user-images.githubusercontent.com/17406355/36266462-2d40f116-127a-11e8-82e8-c433fca30bbb.png)

**Comment by SiarheiSadau** [comment]
> Native volume data column should be in place

@21xhipster , please specify the page

**Comment by SiarheiSadau** [comment]
![exchanges 1](https://user-images.githubusercontent.com/17406355/36310542-12274d78-1331-11e8-9f1c-ddce258a320f.png)

@21xhipster,

> A page of exchange should emphasize it's brand. Huge logo, solid h1
Ok, It will be implemented by @Olga584.

> Please avoid term coin, use token instead
Our idea is to distinguish coins and tokens. Currently we are working only with coins.
