### ISSUE TITLE
Setup ICO page concept 

### ISSUE THREAD

**Issue by litvintech** [cyberFund/cyber-design#22]
- [x] Describe the functions of "ICO List" page:
 - [x] Describe the functions of "ICO Details" page

**Comment by SiarheiSadau** [comment]
ICO List page draft
![ico list](https://user-images.githubusercontent.com/17406355/36377279-45bc41e8-157f-11e8-98d8-008980e5b352.png)

**Comment by SiarheiSadau** [comment]
@Olga584 , ICO details for completed crowdsales. The data in area "Details" can be visualized. 
![ico details](https://user-images.githubusercontent.com/17406355/36420953-61a4a86c-163f-11e8-8f1c-f10ed1f64d61.png)
